### ISSUE TITLE
Exercise_CustomSales

### ISSUE THREAD

**Issue by oviliz** [sankharay/Magento-Update-Guest-Order-Emails-Module#1]
Hi @sankharay , I've installed your extension and it seems working fine on my CE 1.9.1.
Thanks for that!

I've just notice that on the order detail page, apart for the good Edit close to emails, I'm having this text "Exercise_CustomSales" exactly between Shipping Address table and Shipping & Handling Information table, out of any layout.

Is there any reason for that?

**Comment by sankharay** [comment]
Hi

text : Exercise_CustomSales

you can remove. by mistake i left this text in file.
thanks for downloading extension.

**Comment by oviliz** [comment]
Ok, thank you.

I removed the text from app\design\adminhtml\default\default\template\customsales\sales\order\view\info.phtml
line 160 `<div class="clear"></div>Exercise_CustomSales`
